# Generated by Django 3.2.9 on 2021-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muallif', models.TextField(max_length='50', verbose_name='muallif')),
                ('mavzu', models.TextField(max_length='255', verbose_name='mavzu')),
                ('matn', models.TextField(max_length='255', verbose_name='matn')),
            ],
        ),
    ]
